### ISSUE TITLE
Language selection in the native language

### ISSUE THREAD

**Issue by snaggen** [kylewlacy/futura-weather-redux#10]
In my preferences I had for my l10n implementation, I used translated strings for the language names. That way, you don't need to know English to find your language. The strings I used was:
Ok, I can't make this comment system to show the html, you find the html here:
http://snaggen.github.io/futura-weather-redux/v3/preferences.html
....
            <select name="language">
                <option value="0">English</option>
                <option value="1">Svenska</option> //Swedish
                <option value="2">Dansk</option> //Danish
                <option value="3">Nederlands</option> //Netherlands
                <option value="4">Français</option> //French
                <option value="5">Suomi</option> //Finnish
                <option value="6">Deutsch</option> //German
                <option value="7">Italiano</option> //Italian
                <option value="8">Español</option>
                <option value="9">Norsk</option>
            </select>
....

**Comment by kylewlacy** [comment]
Addressed in 9037f307597bdac8cd91eaa209b0ea595dd26d52
(Although this caused another issue, documented [on the Pebble Developer Forums](http://forums.getpebble.com/discussion/10721). This seems to be a minor encoding issue, however)

**Comment by snaggen** [comment]
I wonder if this broke the actual translations? Around 1 AM today the Swedish translation for Sat (Lör) worked fine, then I noticed around 10 AM that it had stopped working. Now when I use Swedish it doesn't show the date at all, the date layer is just blank. The only thing that changed between 1 AM and 10 AM is this checkin (since I didn't upgrade the app) and that I upgraded to RC3 of the firmware. However, I have downgraded to RC2 again just to see if that was the cause, and even with RC2 I cant see the translation so the firmware upgrade was not the cause. 
I wonder if the cause might be the meta charset UTF-8 tag added? Today Saturday and Tomorrow Sunday you may test this easily using Swedish since they both contain the letter ö, "Lör" and "Sön".
