### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by novia713** [kylewlacy/futura-weather-redux#3]
i love this app! thanks!
my mother tongue is spanish and i would like to translate the strings
do you think would be possible to isolate all the strings in one file in next releases to have better and easier way to do the translation?

**Comment by snaggen** [comment]
I have created a branch and added translations, so this issue should be resolved when that branch gets merged. Please review the spanish strings so they are ok.
The strings used are: 
    Months: "Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"
    Days: "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"

**Comment by novia713** [comment]
perfect!!

**Comment by kylewlacy** [comment]
This is in the master branch now, so it should be in the next release.
